### ISSUE TITLE
File Path Error (Windows)

### ISSUE THREAD

**Issue by jasonlbeggs** [calebporzio/better-phpunit#1]
On Windows the relativePath isn’t escaped correctly. Backslashes are removed so it ends up trying to run C:folder1folder2/vendor/bin/phpunit instead of C:\folder1\folder2/vendor/bin/phpunit.

Here is an example:
![image](https://user-images.githubusercontent.com/25065083/32175614-d350afca-bd5b-11e7-912c-f53b9f587c9c.png)

I'm not sure if the issue is happening in the extension code or if VS Code is removing the backslashes after the task has attempted to execute.

**Comment by calebporzio** [comment]
Thanks @jasonlbeggs, haven't tested this on windows, will look into it!

**Comment by calebporzio** [comment]
@jasonlbeggs - try updating the plugin - the problem should be fixed. 

I haven't tested it on a windows machine myself, so let me know if it works and I'll close this issue

**Comment by jasonlbeggs** [comment]
It actually removes all the slashes in the file path now.

![image](https://user-images.githubusercontent.com/25065083/32383863-8dddfd44-c08f-11e7-9572-055b9604304a.png)

I think all the slashes need to be forward slashes for it to work. If I run the following, it works correctly.
```
c:/sites/laravel/ticketbeast/vendor/bin/phpunit c:/sites/laravel/ticketbeast/tests\Unit/ConcertTest.php --filter '/^.*::can_get_formatted_date$/'
```

Do you have a link explaining how to modify and test VS Code extensions? I'd like to help in anyway I can, I'm just not sure how to test it if I change the code.

**Comment by calebporzio** [comment]
Ahhhh we might need to escape the backslashes somehow. hmm.... 

Ya, it' super easy: 

basically, git clone this repo, open it in VS Code, then run the debugger:
https://code.visualstudio.com/docs/extensions/example-hello-world#_running-your-extension
