### ISSUE TITLE
It wont recognize projects with paths including blank spaces

### ISSUE THREAD

**Issue by robsontenorio** [calebporzio/better-phpunit#10]
Better-phpunit wont recognize projects with paths including blank spaces

PATH
```
/Volumes/Backup HD/dev/my-project
               ^ here
```

ERROR 
```
zsh:1: no such file or directory: /Volumes/Backup
The terminal process terminated with exit code: 127
```

**Comment by calebporzio** [comment]
Thanks for reporting this. Fix is in version 0.3.2 and this commit: https://github.com/calebporzio/better-phpunit/commit/0ae35e3dc2d9adc1de01816b2302c0a4237e8a61
