### ISSUE TITLE
Extension runs `phpunit` from root vendor directory where it may not be present

### ISSUE THREAD

**Issue by davidhemphill** [calebporzio/better-phpunit#13]
When running a test inside a project where the root doesn't have a `vendor` directory, running `phpunit` will fail.

```
project
├── package\ 1
│   ├── src
│   ├── tests <-- Running a test from inside here fails
│   └── vendor
└── package\ 2
    ├── src
    ├── tests
    └── vendor
```

**Comment by calebporzio** [comment]
Ahhh, what do you think about this approach?:

> look for `vendor/bin/phpunit`, if file can't be located, just run the `phpunit` command?

**Comment by davidhemphill** [comment]
On [sublime-phpunit](https://github.com/adamwathan/sublime-phpunit), I think we traverse up the tree until we find a directory where there's a `phpunit.xml`, and we run `vendor/bin/phpunit` from there.

**Comment by codycraven** [comment]
I think it would be best to default to vendor/bin/phpunit, however let the user provide another value in their settings.php. I personally have a bash script that wraps a `docker exec` command to run phpunit within a docker container, which means I can not use better-phpunit as it currently stands.

**Comment by jvleeuwen** [comment]
i am having the same issues as @davidhemphill 
i use Orchestra\Testbench\TestCase; and it fails to include this when i use this package as it is included in the package/vendor/.
However i like where this extention is going!
keep up the good work

Kind regards,
Jelle van Leeuwen

**Comment by calebporzio** [comment]
@davidhemphill 0.3.3 uses the traverse up technique to find phpunit.xml and execute `vendor/bin/phpunit` from there. If it doesn find a phpunit.xml, it just executes `vendor/bin/phpunit` from the project root. Update the plugin, test it out and let me know if it fixed it for you

**Comment by davidhemphill** [comment]
@calebporzio Just getting a chance to try this out. I'll let you know. Thanks!

**Comment by davidhemphill** [comment]
@calebporzio Works great!
