### ISSUE TITLE
Not working in VSCode Windows 10

### ISSUE THREAD

**Issue by victormongi** [calebporzio/better-phpunit#14]
> Executing task: c:\Users\......\vendor\bin\phpunit c:\...\tests\Unit\ExampleTest.php --filter '/^.*::testBasicTest$/' <

/usr/bin/bash: c:Users...vendorbinphpunit: command not found
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.

**Comment by calebporzio** [comment]
Can you confirm the version of the plugin you are using?

**Comment by victormongi** [comment]
Better-phpunit from you mate... I ran command better-phpunit run from cmd shift P... and I got the error above... Im running windows 10 machine...

**Comment by antoniopaisfernandes** [comment]
![image](https://user-images.githubusercontent.com/6171197/32939447-698c6cf8-cb77-11e7-9b26-58b9717ccfd0.png)

By removing the slashes, got it to work:

![image](https://user-images.githubusercontent.com/6171197/32939553-c35d0d50-cb77-11e7-8d91-2cb991b05fb0.png)

**Comment by victormongi** [comment]
Anyway where to remove the slashes, Iam sorry, Iam newbie...

**Comment by antoniopaisfernandes** [comment]
I've copied & pasted the command executed by better-phpunit. In my case, it was
```
c:\Users\Antonio\PhpstormProjects\wms\vendor\bin\phpunit c:\Users\Antonio\PhpstormProjects\wms\tests\Unit\Classes\ActivityMapTest.php --filter '/^.*::the_locations_beginning_with_P_go_at_the_end_for_a_single_client_order$/'
```
I've removed the slashes from the filter option:
```
c:\Users\Antonio\PhpstormProjects\wms\vendor\bin\phpunit c:\Users\Antonio\PhpstormProjects\wms\tests\Unit\Classes\ActivityMapTest.php --filter '^.*::the_locations_beginning_with_P_go_at_the_end_for_a_single_client_order$'
```
and executed manually in the terminal. Just to see what change could make it work.

But it needs to be addressed in the package :(

**Comment by calebporzio** [comment]
I removed the slashes in 0.3.3 - let me know if that fixed it, and I'll close the issue

**Comment by tuurbo** [comment]
@antoniopaisfernandes's issue doesnt seem related to @victormongi's post

I'm having the same issue as @victormongi which is "command not found" error.

I installed 0.3.3 and it's not working for me

```
 Executing task: c:\_work\websites\xx\vendor\bin\phpunit c:\_work\websites\xx\tests\Unit\CategoryPageTest.php --filter '^.*::test_should_see_canonical_tag$' <

/usr/bin/bash: c:_workwebsitesxxvendorbinphpunit: command not found
The terminal process terminated with exit code: 127
```

**Comment by calebporzio** [comment]
@tuurbo, ok try 0.3.4

I'm just guessing here because I don't have a windows machine to test this on, so I appreciate the feedback.

**Comment by antoniopaisfernandes** [comment]
@tuurbo For sure. Just a related issue :)

With the latest (at least for me, it works).

👌

**Comment by tuurbo** [comment]
0.3.4 didn't work for me.I have no idea how paths work, but here are the changes I made to get it to work. 

**(only tested on windows 10)**
https://github.com/calebporzio/better-phpunit/compare/a5df6d19a4d32a174f7ad7fda7a728d8319ac3fb...tuurbo:patch-1

**Comment by willsilvano** [comment]
Same issue here.

**Comment by victormongi** [comment]
@tuurbo its working use your patch... I manually modified the extension.js...
![image](https://user-images.githubusercontent.com/5617746/32973843-006a000a-cc35-11e7-910b-af88d53e7dd7.png)

**Comment by calebporzio** [comment]
@tuurbo - K, I converted to forward slashes based on your snippet, let me know if it works.

**Comment by tuurbo** [comment]
@calebporzio Yes, that works, thanks!

But the features mentioned in the readme ```Color output!``` and ```Test failures are displayed in the "Problems" panel for quick access``` don't.

**Comment by calebporzio** [comment]
ughhhh... do you have a phpunit.xml file in your root?

**Comment by tuurbo** [comment]
Yes

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false">
     <testsuites>
        <testsuite name="Feature Tests">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
         <testsuite name="Application Test Suite">
             <directory suffix="Test.php">./tests/unit</directory>
         </testsuite>
     </testsuites>
     <filter>
         <whitelist processUncoveredFilesFromWhitelist="true">
             <directory suffix=".php">./app</directory>
             <exclude>
                 <file>./app/Http/Routes/admin.php</file>
                 <file>./app/Http/Routes/misc.php</file>
                 <file>./app/Http/Routes/store.php</file>
             </exclude>
         </whitelist>
     </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
    </php>
</phpunit>
```

**Comment by calebporzio** [comment]
If you run the command directly in the VS Code terminal do you get colors and problems panel errors?

**Comment by tuurbo** [comment]
Nope, looks like it's not related to your package

**Comment by calebporzio** [comment]
K, I'm going to close this issue then - thanks
