### ISSUE TITLE
Request - Run Full Suite

### ISSUE THREAD

**Issue by JeffBeltran** [calebporzio/better-phpunit#17]
I know i could just run `vendor/bin/phpunit` but would it be possible to add this under the package so i could just add a shortcut and call it good?

**Comment by calebporzio** [comment]
Ya, I agree, I like it. Run folder could be good too.

**Comment by JeffBeltran** [comment]
Awesome, just came back to add the folder/class option too, love me shortcuts 😁

**Comment by calebporzio** [comment]
K, I'm ready to do this thing... programming is so tiring, just for fun I'm going to post my decision making thought process for adding this command here: 
![image](https://user-images.githubusercontent.com/3670578/33506021-df8fac9a-d6bb-11e7-9a1d-7ae24e3d0ce1.png)

**Comment by JeffBeltran** [comment]
haha this is great, but yeah no need to make it more complicated, i just like to run the whole suite once im done to make sure i didn't miss anything and really i have my alias set up so its not a big deal but it would be nice.... also for my tests which are starting to get big i actually have to add the `--process-isolation` flag... so not sure if you can add an option "flag" option 😀

**Comment by calebporzio** [comment]
Ok, version 0.4.1 supports running an entire suite (reference the readme instructions)

**Comment by JeffBeltran** [comment]
@calebporzio Thanks man, just tested it and it works perfectly 🍻
