### ISSUE TITLE
Calling 'run previous' twice while a different file is open gives an error

### ISSUE THREAD

**Issue by ohnotnow** [calebporzio/better-phpunit#2]
(via twitter thread earlier)

If you run a test method, then switch to another file and call 'run previous' twice - the second run will fail - looks like on the 2nd run it's trying to use the currently opened file as the test. Maybe... ;-)

**Comment by calebporzio** [comment]
Thanks - should be fixed now (release 0.3.0)

Be sure to take a look at the new docs, this extension now is supposed to be run from commands, not from the task panel.

**Comment by ohnotnow** [comment]
Yay - works perfectly! Thank you! :-D
