### ISSUE TITLE
Define which PHP binary should be used

### ISSUE THREAD

**Issue by mfour-merickson** [calebporzio/better-phpunit#20]
I receive the following error

```
This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
You are using PHP 5.6.30 (/usr/bin/php).
The terminal process terminated with exit code: 1
```

While this is 'partially' true, the version of PHP I use (version 7.x) is located

```
❯ which php
/usr/local/php5/bin/php
```

Is there a setting I can use to specific the version of PHP which is used>

**Comment by mfour-merickson** [comment]
@calebporzio Further to this, the default installation for macOS these days is indeed `/usr/local/php5/bin/php` so I dont think that `/usr/bin/php` should be used anymore as it is deprecated.

**Comment by mfour-merickson** [comment]
@calebporzio Do you think this is something you are going to be addressing?

**Comment by calebporzio** [comment]
Hey @mfour-merickson - this package just executes the phpunit binary stored in `vendor/bin/phpunit` - it just generates a command (here's a sample one of mine):
```
/Users/calebporzio/Documents/Code/sites/starin-website/vendor/bin/phpunit /Users/calebporzio/Documents/Code/sites/starin-website/tests/Unit/CartTest.php
```
 and runs it in the terminal.

start by copying the command better-phpunit produces into a terminal and seeing what it outputs. If it is still throwing that error, you should be able to fix the issue by changing your global php to point to the 7.X version.

Also, if you can't get any of that to work, I am considering adding a config option for custom phpunit binary, in that case you could point to a phpunit binary that supports 5.3

Try those things and and let me know what comes of it.

**Comment by mikeerickson** [comment]
@calebporzio I had tried the same thing (copy/pasting) the built command `vendor/bin/phunit..` and running it in the integrated terminal and it works fine.

So the commands are basically IDENTICAL, but for some reason, when run as a process entry (as it is in the plugin), it uses a different version of PHP as opposed to other terminals.

```
Also, if you can't get any of that to work, I am considering adding a config option for custom phpunit binary, in that case you could point to a phpunit binary that supports 5.3
```

I am thinking this might be the only other option.

**Comment by calebporzio** [comment]
@mikeerickson / @mfour-merickson - I added a new config item called "phpunitBinary"

Check out version 0.4.1 to use this field to replace this extensions phpunit binary

**Comment by calebporzio** [comment]
Let me know if this helps you with the problem your having

**Comment by mikeerickson** [comment]
@calebporzio well, not quite sure what to say, but this didn't work either (this is really driving me crazy) there should be nothing preventing it from working at this point

```
> Executing task: /usr/local/php5/bin/php /Users/merickson/Documents/code/laravel/l5-sandbox/tests/Unit/ExampleTest.php --filter '^.*::testExample$' <

PHP Fatal error:  Class 'Tests\TestCase' not found in /Users/merickson/Documents/code/laravel/l5-sandbox/tests/Unit/ExampleTest.php on line 7
PHP Stack trace:
PHP   1. {main}() /Users/merickson/Documents/code/laravel/l5-sandbox/tests/Unit/ExampleTest.php:0

Fatal error: Class 'Tests\TestCase' not found in /Users/merickson/Documents/code/laravel/l5-sandbox/tests/Unit/ExampleTest.php on line 7

Call Stack:
    0.0011     357688   1. {main}() /Users/merickson/Documents/code/laravel/l5-sandbox/tests/Unit/ExampleTest.php:0

The terminal process terminated with exit code: 255

Terminal will be reused by tasks, press any key to close it.
```
FWIW, running the exact command in the Integrated Terminal (or iTerm2) all works as expected.

**Comment by mikeerickson** [comment]
@calebporzio Ah, I see the issue.  Had to define setting as

```
    "better-phpunit.phpunitBinary": "/usr/local/php5/bin/php vendor/bin/phpunit"
```
All is now working as expected!!!  Thank you for your efforts, appreciate you adding this property, made the difference.

**Comment by calebporzio** [comment]
perfect, glad to hear it worked!
