### ISSUE TITLE
Don't overwrite "run previous" on test failure

### ISSUE THREAD

**Issue by calebporzio** [calebporzio/better-phpunit#21]
danielcoulbourne [6:26 PM] 
Hey VSCode PHPunit feature request

danielcoulbourne 
[6:26 PM] 
uploaded this image: Screen Shot 2017-11-28 at 6.26.14 PM.png
  Add Comment

danielcoulbourne 
[6:26 PM] 
If I accidentally run phpunit on a file that isn’t a test and get this error

[6:27] 
don’t overwrite CMD+K, CMD+P

[6:27] 
so I can still get back to the old test I was running

**Comment by jasonvarga** [comment]
Was this implemented? I'm constantly hitting the wrong keystroke and testing a non-test method.
It would be a great feature 😊

**Comment by calebporzio** [comment]
No, it's a little trickier than you'd think - I haven't dug deep though and would welcome a PR!
