### ISSUE TITLE
Issue with paths using WSL

### ISSUE THREAD

**Issue by devcircus** [calebporzio/better-phpunit#23]
First, thanks for the great extension. Secondly, this may not be something you can fix, as it may be outside your control.

I'm using the Linux subsystem on Windows 10 and it seems the extension is having a problem reading file paths.

Example:
Using the vscode terminal, I can run my tests with no issues. See below:
![snip_20171204161835](https://user-images.githubusercontent.com/18542852/33579410-5deca53e-d90f-11e7-9ca0-a8da0fba763c.png)

However, using better-phpunit, I get the following error:
![snip_20171204163407](https://user-images.githubusercontent.com/18542852/33579926-fdbdc736-d910-11e7-95f6-4305775cd5d5.png)

As I know the file does indeed exist, this is the only thing I can think may be happening.

Again, if this isn't an issue you can control, no problems.
Thanks

**Comment by devcircus** [comment]
The full suite does run correctly.

**Comment by devcircus** [comment]
ok, i got it working by changing:
```js
    constructor() {
        this.fileName = this.normalizePath(vscode.window.activeTextEditor.document.fileName);
        // ...
}
```
to
```js
        constructor() {
            const originalFileName = vscode.window.activeTextEditor.document.fileName;
            let workingPath = originalFileName.replace(/c:/, "/mnt/c");
            this.fileName = workingPath.replace(/\\/g,"/");
       }
```

Of course this only works on my setup. Basically, Windows accesses C drive through the /mnt directory.

**Comment by calebporzio** [comment]
Hey, thanks for the submitting the issue. I think I'm unclear, is this something people who run linux or windows will run into? or just something specific to your setup? And if that's the case, is there a config option that could provide a fix?

**Comment by devcircus** [comment]
Hey, it's specific to those using the new Linux subsystem in Windows 10, due to the way Windows files are accessed from the Linux filesystem. I'll look into a config option in the coming days. Thanks! If you like, feel free to close this, as it is a very small subset of users that could be affected. If u come up with a solution, I'll submit a PR.

**Comment by devcircus** [comment]
*Should read "If I come up with a solution...". Corrected.

**Comment by calebporzio** [comment]
sweet - closing for now - thanks for offering to PR!!

**Comment by samoldenburg** [comment]
Idea on solution. Easy way to check for WSL on windows might be to check `vscode.workspace.getConfiguration('terminal').integrated.shell.windows`, and see if it is `"c:\\windows\\sysnative\\bash.exe"`.

I don't know if this is robust enough of a check to qualify so I'm not submitting it as a PR.

then this function could be easily changed to support this
```    _normalizePath(path) {
        return path
            .replace(/c:/, this._isWsl() ? "/mnt/c" : "c:") // replace C: with /mnt/c on WSL
            .replace(/\\/g, '/') // Convert backslashes from windows paths to forward slashes, otherwise the shell will ignore them.
            .replace(/ /g, '\\ '); // Escape spaces.
    }
```

**Comment by amadeann** [comment]
I got this working by changing the `ssh.path` setting to what the extension expects. In my case:

```
    "better-phpunit.ssh.paths": {
        "c:/Users/Amade/Code": "/home/vagrant/code"
    }
```

It boils down to replacing backslashes with forward slashes.

Complete settings I am using (I use Laravel Homestead):

```
    "better-phpunit.ssh.binary": "wsl ssh -i /mnt/c/Users/Amade/.ssh/id_rsa",
    "better-phpunit.ssh.user": "vagrant",
    "better-phpunit.ssh.enable": true,
    "better-phpunit.ssh.host": "localhost",
    "better-phpunit.ssh.port": 2222,
    "better-phpunit.ssh.paths": {
        "c:/Users/Amade/Code": "/home/vagrant/code"
    }
```

In addition, I changed the permissions of id_rsa file to 555 with ([some people on SO](https://stackoverflow.com/questions/9270734/ssh-permissions-are-too-open-error) recommend 400 and 600, but they didn't work in my case):

`sudo chmod 555 /mnt/c/Users/Amade/.ssh/id_rsa`

If you're unable to change the file permissions, you may need to run first

```
sudo umount /mnt/c
sudo mount -t drvfs C: /mnt/c -o metadata
```

This will work if you're on Windows 10 Insider Build 17063 or later ([source](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/)).

**Comment by varghesejacob** [comment]
I got better phpunit working on WSL with this batch script.
**Background**: I only have PHP installed inside WSL

First, create a batch script like this and store it somewhere like `C:/php/better-phpunit.cmd`
```
@ECHO off

SET fpath=%CD%
SET fpath=%fpath:C:\=/mnt/c/%
set fpath=%fpath:\=/%

SET testfile=%*
SET testfile=%testfile:C:/=/mnt/c/%

SET cmd=C:\Windows\System32\bash.exe -c "php %fpath%/vendor/bin/phpunit %testfile%"

CALL %cmd%
```

Next, add this to your settings.json: `"better-phpunit.phpunitBinary": "C:/php/better-phpunit.cmd",`

Now you should be able to run better-phpunit if you only have php installed inside WSL.

What this script does is replace `C:\` with `/mnt/c` since that is how windows folders are accessed from inside WSL. For example, if your website is stored at `C:/code/yourproject`, then WSL can access it by `/mnt/c/code/yourproject`

Hope this helps someone.

**Comment by rginnow** [comment]
@samoldenburg Can confirm your solution works. The only problem I had was that the path to the bash.exe was case-sensitive, and my code is on my W drive, not C drive.

```
    _normalizePath(path) {
        return path
            .replace(/w:/, this._isWsl() ? "/mnt/w" : "w:") // replace w: with /mnt/w on WSL
            .replace(/\\/g, '/') // Convert backslashes from windows paths to forward slashes, otherwise the shell will ignore them.
            .replace(/ /g, '\\ '); // Escape spaces.
    }

    _isWsl() {
        return vscode.workspace.getConfiguration('terminal').integrated.shell.windows == "c:\\windows\\sysnative\\bash.exe" // This was case sensitive - must match user settings
      }
````
