### ISSUE TITLE
The task 'phpunit: run' is already active.

### ISSUE THREAD

**Issue by faustbrian** [calebporzio/better-phpunit#24]
I am experience some weird problem when trying to use this extension. I installed it and tried to run my tests through this extension but after running my tests for the first time and then trying to execute another test it will show me this error message.

`The task 'phpunit: run' is already active. To terminate it use 'Terminate Task...' from the Tasks menu.`

What I can see is that the terminal is stuck after the `OK (1 test, 2 assertions)` and the cursor just continues to blink and I have hit enter twice to kill the process and get the terminal back into a state where I can type.

If I run the same same command it executes when I hit `cmd+k cmd+r` the terminal or phpunit doesn't get stuck after finishing the test execution.

Any idea what could cause this?

**Comment by calebporzio** [comment]
The only time I see that is when I try to run another test while one is running, which is to be expected.

That's weird though - I really don't know where to start debugging. I've considered switching the implementation of this package to straight terminal instances instead of tasks - that would give us more control over situations like these.

Let me know if there's anything you can think of trying to get past this - thanks

**Comment by faustbrian** [comment]
Yeah, the part of a running test I figured but it even happens with one liner tests like `$this->asserTrue(true);`. It will just get stuck and expect me to hit enter before I can run the next test.

I will try to play around with it a bit during the weekend, maybe I break something by accident that causes the problem :fire:

**Comment by calebporzio** [comment]
Great, keep me posted - thanks

**Comment by calebporzio** [comment]
Closing this for now

**Comment by joedixon** [comment]
Did you have any luck with this @faustbrian?

I'm having the same problem. Additionally, I get no output in the problems panel.

![screen shot 2018-01-02 at 11 38 33](https://user-images.githubusercontent.com/3438564/34482711-a6f5ff06-efb1-11e7-8581-e7026c471993.png)

![screen shot 2018-01-02 at 11 38 50](https://user-images.githubusercontent.com/3438564/34482715-aa9537a8-efb1-11e7-9b33-1541315622fa.png)

**Comment by enricodias** [comment]
I've been using this extension for a long time and I just started to have this problem. The terminal doesn't get stuck and everything works, but the task remains active on vscode. This happens regardless of the actual test results and the problems panel gets no output.
