### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by set0x** [calebporzio/better-phpunit#26]
If dont use putty dont work.

```js
get binary() {
    if (this.isRunningOnWindows) {
        return "putty -ssh";
    }

    return "ssh";
}
```

If better can configure by user settings.
```js
get binary() {
    return this.config.get("ssh.binary");
}
```

**Comment by calebporzio** [comment]
@set0x - ok - there is now a config option for this: `ssh.binary`

Try it out and let me know if it works - thanks!
