### ISSUE TITLE
phpunit.xml ignored

### ISSUE THREAD

**Issue by petercoles** [calebporzio/better-phpunit#30]
It appears that when a workspace contains multiple projects organized into folders, then this plugin ignores or fails to find the .xml settings file, when tests are run for one of the projects - though it does run the local version of phpunit (i.e. vendor/bin/phpunit) rather than any available globally or elsewhere in the workspace.

This appears to the be root cause of the colorisation problem reported in https://github.com/calebporzio/better-phpunit/issues/22.

**Comment by calebporzio** [comment]
Thanks for discovering this @petercoles - it should be fixed in the latest release (0.6.0)

**Comment by petercoles** [comment]
Working and making my life easier and more colorful! Many thanks.

**Comment by petercoles** [comment]
Sorry, partial retraction. This works, except when running a full test suite, when the settings file is still ignored.

It looks to me as though the ${configuration} string is needed for the full suite as well (phpunit-command.js line 20), i.e. on the only difference between full suite and test file should be the absence of a filter.

Apologies for mot being able to construct a pull request with tests. I'm overdue on adding mocha to my repertoire. :(

**Comment by yhalabi** [comment]
any temporary patch you could recommend? 
I'm using two databases, one for phpunit and one for local machine, and it keeps reseting migrations and everything on local machine when using the plugin, it kind of defeats the purpose of test automation :/

thanks for the awesome plugin btw

**Comment by yhalabi** [comment]
appending --configuration was a fast fix for me
thx anyway

**Comment by SimonJ** [comment]
@yhalabi Where did you append that too :)?
