### ISSUE TITLE
It always ask me to select the task to run.

### ISSUE THREAD

**Issue by alexjoffroy** [calebporzio/better-phpunit#33]
Hi,

When I run the command "Better PHPUnit: run", VSCode always asks me to select task and do not run the task automatically (as I expected first). Is it the normal behavior ? 

![capture d ecran 2018-01-18 a 19 29 39](https://user-images.githubusercontent.com/7209163/35114722-fc8e8920-fc85-11e7-89f6-a9d67bbf004b.png)
![capture d ecran 2018-01-18 a 19 29 48](https://user-images.githubusercontent.com/7209163/35114724-fe99ce78-fc85-11e7-946b-d84149daea68.png)

Nice extension, nevertheless !

**Comment by stefanbauer** [comment]
Same here, but with the difference, i don't see the `phpunit: run` command. See #34 - maybe this has to do something with it? Dunno.

**Comment by alexjoffroy** [comment]
Really weird, but yesterday I installed VS Code with all my extensions on my home computer, and it worked fine. 

This morning, I deleted VS Code  from my work computer (removing the actual app and also the `~/.vscode` directory). Then I reinstalled a clean version and imported all my extensions/settings (with the settings-sync extension), and now it works ! 😲

**Comment by stefanbauer** [comment]
I tried the same, here nothing changed.

**Comment by alexjoffroy** [comment]
Weird. At first, I thought it was a conflict with my NPM tasks, but I also reinstalled them and it works. Did you register some other tasks ?

**Comment by stefanbauer** [comment]
Unfortunately not. Tried 3 times with a complete fresh installation without doing anything else.

**Comment by alexjoffroy** [comment]
Did you also remove your `~/.vscode` directory ?

Other thought, do you use phpunit globally ? If so, did you try to install it locally (`./vendor/bin/phpunit`) ?

**Comment by stefanbauer** [comment]
Yes, removed `~/.vscode` and no, not using it globally. Always project related :)

**Comment by alexjoffroy** [comment]
Erf. No more idea. I hope someone will help you !
And I'm curious to know why, 'cause I don't like to fix bugs without knowing how 😅

**Comment by stefanbauer** [comment]
I installed now PHPUnit Extended. Has quite the same features (but bit more). With that, everything is working as expected! Thanks anyways :)

**Comment by alexjoffroy** [comment]
I close. If it happens to someone else, feel free to reopen !

**Comment by andreich1980** [comment]
Same story here. 

I open my test class, 
I run `Better PHPUnit:run`, 
![image](https://user-images.githubusercontent.com/17148882/41191875-65c29bc4-6bfe-11e8-9b53-b74e8a75eb9c.png)

it shows `select the command to run` with options like `npm dev` etc (similar to the @alexjoffroy 's screenshot but for me it doesn't contain `phpunit: run` task
![image](https://user-images.githubusercontent.com/17148882/41191888-9db8546a-6bfe-11e8-951d-1b2645177233.png)

This started recently, I don't remember I installed any extentions. I think it started after a vs-code update (I'm on Insiders edition)

The docs says 

> Note: this plugin registers "tasks" to run phpunit

but there's no such a task. 
Can I add it manually? I guess I should add it in the `tasks.js` but I'm confused what exactly to add.

Help me please.

Version 1.25.0-insider
Commit 8f8ed32e737a7a906fac654fb0bd61b257b449b1
Date 2018-06-08T05:20:32.976Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by andreich1980** [comment]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#Task

Seems that the old version of `Task` constructor is deprecated.

**Comment by rizerzero** [comment]
same here :(

![image](https://user-images.githubusercontent.com/1518379/44950821-50be4c00-ae52-11e8-8019-372ade8d1b22.png)

**Comment by barrykeenan** [comment]
I have the same problem as of this morning.

**Comment by stillzombie** [comment]
Same problem here, any solutions?

**Comment by nexxai** [comment]
Dammit, now it's happening to me too

**Comment by FelixAuer** [comment]
I've got the same. Was there an update that broke something?

**Comment by jdavidbakr** [comment]
Same problem here, suddenly started happening today.

**Comment by Cklauber** [comment]
Same problem here.

**Comment by jason-guru** [comment]
I was working a few days back, now I am having the above mentioned issue.

**Comment by calebporzio** [comment]
See my comment on issue #52: https://github.com/calebporzio/better-phpunit/issues/52#issuecomment-462057076
