### ISSUE TITLE
Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by stefanbauer** [calebporzio/better-phpunit#34]
Is there anything known? If i run `Better PHPUnit: run`, then this error occurs. Tried now in a complete fresh vscode installation to start really from scratch, cause i thought something else is responsible for this problem. But it isn't. 

Tried setting `better-phpunit.phpunitBinary` to null, to `phpunit` ($PATH is added), relative path and absolute path. Nothing is working. Do you have an idea? Didn't even know if it's a better-phpunit package problem. But i am sure, you know it :)

**Comment by stefanbauer** [comment]
Awesome @sixlive :) Great work! That makes perfect sense. I think that could solve it. Will test it later. Thanks man!

**Comment by sixlive** [comment]
#40 was merged and `0.7.0` was released. You should be able to update the package in vscode and test it out, hopefully it fixes your issue!

**Comment by calebporzio** [comment]
Closing for now - thanks @sixlive (re-open if that wasn't the fix)

**Comment by stefanbauer** [comment]
Wuhuuu! Tested and it is working :) Thanks @calebporzio and @sixlive 👍

**Comment by sixlive** [comment]
Awesome!!!

**Comment by marcelloh** [comment]
I have the same message:
Error: Path must be a string. Received null
and using: .tests/phpunit_all.xml
what can I do to solve it?

**Comment by sixlive** [comment]
@marcelloh currently the only file names supported are `phpunit.xml` and `phpunit.xml.dist`. I feel like these file names are pretty standard for applications and packages.

**Comment by sixlive** [comment]
@calebporzio maybe we can add an override configuration array of file names to try?

**Comment by sixlive** [comment]
Maybe related to #63 ?

**Comment by calebporzio** [comment]
#63 merged - thanks guys!

**Comment by bm-stschneider** [comment]
I still have this issue
