### ISSUE TITLE
Run tests in an external terminal

### ISSUE THREAD

**Issue by helilabs** [calebporzio/better-phpunit#36]
Hi
I really love vscode but i really hate vscode integrated terminal and i love to work on an external terminal, accordingly I'd love my tests to be run on the external terminal and I'm really willing to make a PR to do so. but i have to problems

1. I can't understand this particular line in your code 
```
    await vscode.commands.executeCommand('workbench.action.tasks.runTask', 'phpunit: run');
```
as far as i can understand this line run a task called "phpunit: run" but i can't find where is task defined ?

2. I already thought of the code to open and execute the test command but i have no idea on how to test it
```
    var osascript = require('node-osascript')

    console.log(osascript)
    command = []
    command.push('tell application "iTerm2"');
    command.push('	tell current session of first window');
    command.push('		activate current session');
    command.push('		write text code');
    command.push('	end tell');
    command.push('end tell');
    command = command.join('\n');

    osascript.execute(command, {code: this.lastOutput}, function (error, result, raw) {
        console.log(code);

        if (error) {
            console.error("An error occurred: ");
            console.error(error);
        }
    });
``` 

thoughts ?

**Comment by calebporzio** [comment]
ya something like this is outside the scope of the package in it's current implementation. Dig through the extension.js file to find the Task definition.

If you can think of a way to get this in, test it and keep it backwards compatible I would welcome a PR - but no plans for now - thanks!
