### ISSUE TITLE
phpunit.xml path reverts back to local path when using remote phpunit command

### ISSUE THREAD

**Issue by crazyfoolmurdock** [calebporzio/better-phpunit#42]
Hi,
I was trying to get this to work in windows 10 wsl with a linux vm as my dev server.  Whenever I run a command it seems to convert the local php file path correctly but then forgets about xml file path so we get:-

`"www/GraphProject/vendor/bin/phpunit /home/dev/www/GraphProject/t/helpers/CGraphTest.php --filter '^.*::test_ArchiveGraph_renames_file_by_adding_suffix$' --configuration t:/GraphProject/t/phpunit.xml"`

It appears that the `phpunit-command.js` can be modified to:-

`get configuration() {

        let filePath = this._phpunitXmlPath();
        return filePath
            ? ` --configuration ${filePath}`
            : '';
    }

    _phpunitXmlPath {
        return this.subDirectory
            ? ` ${this._normalizePath(path.join(this.subDirectory, 'phpunit.xml'))}`
        : '';
    }`

 And then the `remote-phpunit-command.js` needs the following (or something like it)

`get configuration() {
    let filePath = this._phpunitXmlPath();
        return filePath
            ? ` --configuration ${this.remapLocalPath(filePath)}`
            : '';
    }
`

This could do with a test before it goes in as Im not that big on javascript.

**Comment by calebporzio** [comment]
This should be fixed by #45 -> upgrade to version 0.8
