### ISSUE TITLE
Configure buffer length of test output

### ISSUE THREAD

**Issue by jdavidbakr** [calebporzio/better-phpunit#43]
I have a test in a Laravel project that, when it fails, shows the error message 'Failed asserting that <entire html of page> did not contain <string I'm looking for>'.  Occasionally this message is too long for the buffer and the actual string that I'm testing for is not visible.  Would it be possible to add as a configuration the number of lines that the script outputs?  Not sure if that's a limitation of this package or of VS Code (although running the script in the VS Code terminal doesn't truncate the output)

**Comment by calebporzio** [comment]
I believe this is a limitation of Tasks in VS Code - if/until we update the implementation we will keep this in mind - thanks!
