### ISSUE TITLE
A new cmd.exe window is opened when running tests

### ISSUE THREAD

**Issue by BrightSoul** [calebporzio/better-phpunit#47]
Hi there, every time I run a test or the entire suite, a new cmd.exe opens. Instead, I'd like to see the output in the "Task - run" panel inside Visual Studio Code. What should I do to fix this? I'm running VSCode v1.22.2 and Better PHPUnit v0.7.0 on Windows 10. I didn't change any terminal-related options, I'm using the default one (powershell).
![image](https://user-images.githubusercontent.com/1888641/39294785-ec6567ea-493c-11e8-9790-e5788110c417.png)

 I just changed the keybindings from Windows+K, Windows+R (which obviously didn't work) to Control+K, Control+R.
![image](https://user-images.githubusercontent.com/1888641/39294917-3bb33048-493d-11e8-98ba-45b412d6c454.png)

This is my first time using Better PHPUnit, so the cause might some bogus configuration on my part. Here's my user configuration.
```
{
    "git.ignoreMissingGitWarning": true,
    "git.autofetch": true,
    "window.zoomLevel": 0,
    "php.validate.enable": true,
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "php.validate.run": "onType"
}
```

And my phpunit.xml file contents
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
    </testsuites>
    <filter>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
    </php>
</phpunit>
```

Thanks in avdance

**Comment by oliveready7** [comment]
Also came across this error.

The solution was to simply update VsCode to v1.25.

**Comment by calebporzio** [comment]
Great! I'm going to close this then.

**Comment by ABQJuan** [comment]
I am running vscode 1.32.3 on Windows 10 and when I run a test with Better PHPUnit, a new cmd window is launched and when the test is finished the cmd window closes immediately making seeing the results of the test impossible. Besides updating VsCode to 1.25 mentioned above, is there a fix for this behavior? 

Also, I am using powershell as the terminal in VsCode, but have tested using wsl and git-bash as the terminal and get the same behavior.

**Comment by ABQJuan** [comment]
UPDATE: A fix for the cmd window closing automatically after the tests complete is to add a PAUSE command at the end of the phpunit.bat file in the vendor->bin folder. 

ALSO:
I switched the default terminal in VsCode to git-bash and now the it spawns a new internal terminal window in VsCode rather than spawning an external cmd window when using Powershell. I would rather be in PS so I'll go back to the pausing cmd window. (I hate developing in Windows)
