### ISSUE TITLE
Something is wrong with creating tasks for the Better PHPUnit command

### ISSUE THREAD

**Issue by andreich1980** [calebporzio/better-phpunit#52]
Probably related with #33 (my 2 last comments there)

https://code.visualstudio.com/docs/extensionAPI/vscode-api#Task
Seems that the old version of Task constructor is deprecated.

I'm absolutely newbie in extentions so I can't tell more than this my little research.

> Windows 10
> Version 1.25.0-insider
> Commit 8f8ed32e737a7a906fac654fb0bd61b257b449b1
> Date 2018-06-08T05:20:32.976Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

**Comment by andreich1980** [comment]
My .vscode/tasks.json looks like this
```
{
    // Seehttps://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "production",
            "problemMatcher": []
        },
        {
            "type": "npm",
            "script": "dev",
            "problemMatcher": []
        }
    ]
}
```

So, there's no any `phpunt` related tasks.

**Comment by andreich1980** [comment]
It's worked well in a fresh installation of `VS Code`. Seems it only fails in `VS Code Insiders`

**Comment by JulianMar** [comment]
Hi.

I created a [PR](https://github.com/calebporzio/better-phpunit/pull/53) to fix this issue. 
I used the new [Task](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Task) constructor like you suggested. 
Tests can now be run by everyone aswell.

**Comment by andreich1980** [comment]
@JulianMar thanks a bunch!

**Comment by JulianMar** [comment]
Now we just need someone to check it and merge it.

**Comment by JulianMar** [comment]
it seems like it still isn't fixed I will take another look.

**Comment by R3l4x3** [comment]
@JulianMar Is there a way to use your change now before the pull request has been merged?

**Comment by calebporzio** [comment]
I'll get this merged in a minute, let me just pull it down and check it works

**Comment by andreich1980** [comment]
@calebporzio would my idea work? Could I make a change locally in the extensions folder? Or I need to recompile it?

**Comment by JulianMar** [comment]
@R3l4x3 You can checkout my branch locally and open it with vscode-insiders. You can launch a new instance with the changes if you run the Extension config. 

In the new window you can open any PHP Project and try it out.

**Comment by R3l4x3** [comment]
@calebporzio That's good to hear!

@JulianMar Thanks, that's how it works. I felt, however, that the extension now works differently than before.

**Comment by JulianMar** [comment]
@R3l4x3 Yeah it works differently. It now runs the command in a shell and not as a task. It was quite difficult to get the task setup with the [task v2](https://code.visualstudio.com/docs/editor/tasks) API. 
The [documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_tasks) is lackluster and the [example](https://github.com/Microsoft/vscode-extension-samples/tree/master/task-provider-sample) wasn't great either. 
So for a quick fix I run the Task in the shell. If you have a better grasp of the task API and can get it to work, I would be happy

**Comment by R3l4x3** [comment]
@JulianMar Ah okay, I get it!
It's important to me that it works. Just wanted to mention it. 🙂
I am new to VSCode, so I have no experience in extension programming.

Thanks for the quick fix!

**Comment by calebporzio** [comment]
Sorry, I didn't merge that PR. I thought it used Tasks still. The straight terminal approach won't work. It opens a new terminal window for each test run. I'd rather use Tasks still if at all possible. The tasks API has always been super tough to work with.

If I get a chance, I'll try to get this working in VS Code Insiders.

Any help here is appreciated.

**Comment by JulianMar** [comment]
I will have another look aswell. 
@calebporzio if you merge my new PR #54 more people could try it out. It was quite hard to get the project setup at the beginning.

**Comment by calebporzio** [comment]
Anyone else having problems now running the tests?

**Comment by R3l4x3** [comment]
@calebporzio I'm not that experienced in Javascript testing, so I don't know if I did everything right. But I always get error messages.

> Error: cannot open file:///Users/R3l4x3/Sites/gitHub/better-phpunit/test/tests/SampleTest.php. Detail: File not found (file:///Users/R3l4x3/Sites/gitHub/better-phpunit/test/tests/SampleTest.php)

The right path would be `file:///Users/R3l4x3/Sites/gitHub/better-phpunit/test/project-stub/tests/SampleTest.php`

What I did:
- cloned repo
- run `npm install` in project folder
- run `npm test` in project folder and in test folder (both with same result)

**Comment by JulianMar** [comment]
@R3l4x3 you have to run ```Extension:test``` in the debug menu. 
It should work after that.

**Comment by R3l4x3** [comment]
@JulianMar Thank you. Now it grabs the right path.

But all tests are still failing. Apparently it can't access `extension.getGlobalCommandInstance()`, because I always get an error when a property is used afterwards. 

For example:

> Run file outside of method:
    Uncaught TypeError: Cannot read property 'method' of undefined
      at timeout (/Users/R3l4x3/Sites/gitHub/better-phpunit/test/extension.test.js:40:59)
      at Timeout.setTimeout (/Users/R3l4x3/Sites/gitHub/better-phpunit/test/extension.test.js:11:13)

or

> Detect filename:
     Uncaught TypeError: Cannot read property 'file' of undefined
      at timeout (/Users/R3l4x3/Sites/gitHub/better-phpunit/test/extension.test.js:77:53)
      at Timeout.setTimeout (/Users/R3l4x3/Sites/gitHub/better-phpunit/test/extension.test.js:11:13)

**Comment by JulianMar** [comment]
I forgot to adapt the launch configuration a little bit. #56

**Comment by R3l4x3** [comment]
I changed the file locally and now it is working
> 16 passing (14s)

**Comment by VincentKos** [comment]
same problem and I don't use the insider version.

**Comment by calebporzio** [comment]
This if frustrating. VS Code changed Task definitions in v1.31 to not support the syntax better-phpunit currently uses. I verified that the extension works on v1.30, and developed a fix for v1.31. I will watch for it's release and update it.

That's odd that you are having problems @VincentKos in a non-insider version. Can you provide more details? What VS Code version are you using? What Better PHPUnit version are you using?

**Comment by ahinkle** [comment]
@calebporzio VSCode v1.3.1 dropped today and broke my extension as well. 

![Image](https://media.giphy.com/media/MuE9K08i63BYDwOGPM/giphy.gif)

**Comment by jakebathman** [comment]
Yep, same issue here on the public release channel (v1.30.2). 

As a workaround for anyone affected, you can add a definition in your `package.json` file in the `scripts` section:

```json
"scripts": {
  ...
  "test": "phpunit"
  ...
}
```

And at least that'll give you the option in the "Select the task to run" prompt.

**Comment by calebporzio** [comment]
Thanks for the workaround Jake!

If the package broke for you, you are either:
A) On a NEWER version of code and HAVEN'T updated the extension
B) On an OLDER version of code but HAVE updated the extension

The proper versions that should be working are:
VS Code: v1.31.0 or above
Better PHPUnit: 1.3.2

Sorry for the lameness everyone!
