### ISSUE TITLE
Config to specify path to phpunit.xml(.dist)

### ISSUE THREAD

**Issue by semicullen** [calebporzio/better-phpunit#65]
My project has an unusual structure:

```
root/app/phpunit.xml.dist
root/src/*.php
```

By default, better-phpunit doesn't detect the phpunit.xml file and gives the same error as reported [here](34)

I'm hoping for an extra config param to specify a custom path to the phpunit.xml file.

**Comment by sixlive** [comment]
Maybe related to #63 ?

**Comment by semicullen** [comment]
Yep, looks like that should address this.

**Comment by calebporzio** [comment]
#63 has been merged - sorry for the wait
