### ISSUE TITLE
Running specific test methods is broken

### ISSUE THREAD

**Issue by mwkcoding** [calebporzio/better-phpunit#67]
The code that's supposed to run the specific method has syntax errors in the regexp

Look at the following:

`return this.method ?  --filter '^.*::${this.method}( with data set .*)?$' : '';`

The "`(with data set .*)`" should just be "`.*`" otherwise it just keeps saying no tests executed.

**Comment by garygreen** [comment]
Getting the same problem. Must be a recent vscode update that's causing it to be incompatible with this extension anymore?

![image](https://user-images.githubusercontent.com/1702638/46484878-8c05bf00-c7f2-11e8-8f92-b9101cccc97a.png)

**Comment by garygreen** [comment]
For anyone else who stumbles across across this, until that broken commit is reverted / fixed, you can downgrade to previous version of this extension by following these instructions. Hope it helps

https://github.com/Microsoft/vscode/issues/12764#issuecomment-410571200

**Comment by mwkcoding** [comment]
You can also, just go into the source file of the extension and change it. I think it was in index.js or something. That also fixes it.

**Comment by garygreen** [comment]
Well looks like I completely messed up the extension locally now. Can't install it at all now and command isn't found. Bummer :/

**Comment by calebporzio** [comment]
I'll get this reverted ASAP

**Comment by calebporzio** [comment]
Ok, I reverted and published 1.1.0 - issue should be fixed - re-open if not.
