### ISSUE TITLE
Possible enhancements?

### ISSUE THREAD

**Issue by thecrypticace** [calebporzio/better-phpunit#7]
I'd like to investigate semi conversion to TypeScript as well as some structural changes to aid readability and focus.

The move to TypeScript really would be to enable ES6 module support. The type declarations are okay too I guess. :P

1. Setup TypeScript compilation or w/e. I think VSCode can directly run TypeScript so a compilation build-setp _may_ not be necessary but I need to look into it a bit more.
2. ES6-style imports and exports. I've gotten so used to writing `import …` and `export …` that it feels strange to use `require` and `exports.whatever = …` again.
3. Moving source code into a `src/` directory. Currently the extension file is in the root. When more folders and files get added it'll definitely help having a folder dedicated to source code so other files can get out of the way.
4. An ESLint file is present already but it doesn't appear to be based on a given standard (maybe? idk) So some things can be inconsistent and still appear okay.
5. There's currently no linting step setup might be worth doing as well

In lieu of enabling TypeScript there could also be a build step to compile ES6 modules to CommonJS exports.

**Comment by calebporzio** [comment]
True, all of the above will be good things when the extension grows. For now, I just love only having one simple, explicit, file to maintain
