### ISSUE TITLE
Windows 10 can t run single test

### ISSUE THREAD

**Issue by ruibranco** [calebporzio/better-phpunit#78]
When i try to tun the php better, if i do it from my cmd, it executes all without problem, when i try to run better php with in the vs, it can t, especially single function that i want to run! It also ask me how i want to open the file????!!!!

![capturar](https://user-images.githubusercontent.com/43033565/48341898-3a104e80-e666-11e8-9621-0d5294a76f8b.PNG)

i ve already edited the json file, and all that, still not working

Thank you

**Comment by calebporzio** [comment]
Unfortunately, I can't test it because I don't have a Windows machine - is anyone else able to pitch in here?
