### ISSUE TITLE
broken keybinding for windows

### ISSUE THREAD

**Issue by iteniasim** [calebporzio/better-phpunit#88]
## What are the steps to reproduce this issue?

1. just check the default keyboard shortcuts after installing better phpunit.

## What happens?
…win+k win+r cannot be pressed in vscode. As soon as you press win key, start menu opens and its already out of the scope of vscode.

## What were you expecting to happen?
…some keybinding that at least works out of the box

## What versions are you using?
**Operating System:** …Windows 10
**Package Version:** …Latest atm(1.3.1)

**Comment by calebporzio** [comment]
I honestly don't have a windows machine. A PR to fix this would be very helpful. Is that something you're capable / willing to do?

**Comment by iteniasim** [comment]
Nope. Not capable of editing any extentions, new to programming and i know just the basics so..
and this is what works for me although i dont know how to fix it for a PR. 
![Capture](https://user-images.githubusercontent.com/31771642/61604250-7c137a80-ac60-11e9-8dc5-4ff81f127f0f.PNG)

**Comment by Pen-y-Fan** [comment]
I'm a windows user, both windows 7 and 10. I can change the keybindings. I currently have them mapped CTRL + T to run a test and CTRL + SHIFT + T to re-run a test

See Jeffery Ways video on how to set up Better PHPUnit in VS Code:  https://laracasts.com/series/visual-studio-code-for-php-developers/episodes/10

To change the keymap either user CTRL K CTRL S or File> Preferences> Keymaps

One point of note, if the keybindings are already mapped to an existing extension, an error will display, stating the keymap is already in use. Click the error link to that extension and change the key bindings to another unique map, then go back to better PHPUnit to choose the required bindings.
