### ISSUE TITLE
Clear the terminal output before running a test.

### ISSUE THREAD

**Issue by wilburpowery** [calebporzio/better-phpunit#9]
I think it is easier to visualize the current test if we clear the Terminal output. At the moment, it just keeps appending all output to the console. I have to manually clear my console. 

I can PR it. Just let me know. 😊

**Comment by chriys** [comment]
@wilburpowery as a User I'll definitely be greatlful for this addition. will make things easier.

**Comment by wilburpowery** [comment]
This issue will be solved by PR [#12](https://github.com/calebporzio/better-phpunit/pull/12) 👍🏻🤠

**Comment by calebporzio** [comment]
Thanks @wilburpowery!
