### ISSUE TITLE
Is there a way to run all the test of the file?

### ISSUE THREAD

**Issue by jopereyral** [calebporzio/better-phpunit#98]
## Summary
What I'm think is some command that can run for all the tests in the file, for the moment I use run previous tests, but sometimes my file tests is too long.

## Possible Implementation Ideas
I think it can be solved by the same strategy is used for run individual tests

**Comment by calebporzio** [comment]
I just added a "better-phpunit.run-file" command that will accomplish what you want. It is included in the latest version (1.5)
